import type {Deal,DealOffer} from "../types.js";
import {comparablePrice,offerIdentity,summarizeHistory} from "./history.js";
import {scoreDeal} from "./score-deal.js";
import type {BestDealsData,HistoricalObservation,RankedDeal} from "./types.js";

export function enrichDeals(deals:Deal[],history:Map<string,HistoricalObservation[]>):Deal[]{
  return deals.map(deal=>{const offers=deal.offers.map(offer=>{const value=comparablePrice(offer),rows=offerIdentity(offer)?history.get(offerIdentity(offer)!)??[]:[],intelligence=scoreDeal(offer,summarizeHistory(value.price,value.unit,rows));return{...offer,intelligence}});const comparable=offers.filter(offer=>offer.channel!=="online"&&offer.pricePerUnit!=null&&offer.pricePerUnitType),units=new Set(comparable.map(offer=>offer.pricePerUnitType));if(new Set(comparable.map(offer=>offer.store)).size>1&&units.size===1){const sorted=[...comparable].sort((a,b)=>a.pricePerUnit!-b.pricePerUnit!),best=sorted[0],next=sorted.find(offer=>offer.store!==best.store);if(next&&best.pricePerUnit!<next.pricePerUnit!){best.intelligence.comparisonReasons.push("CHEAPEST_TRACKED_STORE");best.intelligence.cheaperThanTrackedBy=Number((next.pricePerUnit!-best.pricePerUnit!).toFixed(2));best.intelligence.cheaperThanTrackedPercent=Number((((next.pricePerUnit!-best.pricePerUnit!)/next.pricePerUnit!)*100).toFixed(1))}}return{...deal,offers}});
}
function toRanked(deal:Deal,offer:DealOffer):RankedDeal{return{rank:0,dealId:deal.id,product:deal.name,category:deal.category,store:offer.store,sourceName:offer.sourceName,salePrice:offer.salePrice,regularPrice:offer.regularPrice,pricePerUnit:offer.pricePerUnit,pricePerUnitType:offer.pricePerUnitType,discountPercent:offer.intelligence?.advertisedDiscountPercent,validUntil:offer.validUntil,sourceUrl:offer.sourceUrl,promotionType:offer.promotionType,dealScore:offer.intelligence?.dealScore??0,reasons:offer.intelligence?.reasons??[],historicalStatus:offer.intelligence?.historicalStatus??"INSUFFICIENT_HISTORY"}}
const stableSort=(a:RankedDeal,b:RankedDeal)=>b.dealScore-a.dealScore||(b.discountPercent??-1)-(a.discountPercent??-1)||a.product.localeCompare(b.product,"en")||a.store.localeCompare(b.store)||a.sourceName.localeCompare(b.sourceName,"lt");
function diversify(rows:RankedDeal[]){const head:RankedDeal[]=[],deferred:RankedDeal[]=[],counts=new Map<string,number>();for(const row of rows){const count=counts.get(row.category)??0;if(head.length<10&&count<3){head.push(row);counts.set(row.category,count+1)}else deferred.push(row)}return[...head,...deferred]}
export function rankDeals(deals:Deal[],generatedAt:string):BestDealsData{const active=deals.flatMap(deal=>deal.offers.filter(offer=>offer.channel!=="online").map(offer=>toRanked(deal,offer))).sort(stableSort),rank=(rows:RankedDeal[])=>diversify(rows).map((row,index)=>({...row,rank:index+1}));return{generatedAt,all:rank(active),byStore:{rimi:rank(active.filter(row=>row.store==="rimi")),maxima:rank(active.filter(row=>row.store==="maxima"))}}}
