import {readdir,readFile} from "node:fs/promises";
import {isExcludedPorkProduct} from "../exclusions/pork.js";
import type {Deal,DealOffer,UnitType} from "../types.js";
import type {HistoricalObservation,HistorySummary} from "./types.js";

export const MIN_HISTORY_OBSERVATIONS=3;
export const NEAR_LOW_THRESHOLD=.05;
function platform(offer:DealOffer){return offer.sourcePlatform??offer.store}
export function offerIdentity(offer:DealOffer){const scope=`${offer.store}|${platform(offer)}|${offer.channel??"physical"}`;if(offer.externalId)return`${scope}|external:${offer.externalId}`;if(offer.canonicalProductId)return`${scope}|canonical:${offer.canonicalProductId}`;return undefined}
export function comparablePrice(offer:DealOffer){return offer.pricePerUnit!=null&&offer.pricePerUnitType?{price:offer.pricePerUnit,unit:offer.pricePerUnitType}:{price:offer.salePrice,unit:undefined}}
export async function loadHistory(directory="data/history"){const observations=new Map<string,HistoricalObservation[]>();let files:string[]=[];try{files=(await readdir(directory)).filter(file=>/^\d{4}-\d{2}-\d{2}\.json$/.test(file)).sort()}catch{return{files,observations}}for(const file of files){let deals:Deal[];try{deals=JSON.parse(await readFile(`${directory}/${file}`,"utf8")) as Deal[]}catch{continue}for(const offer of deals.flatMap(deal=>deal.offers)){if(offer.store!=="rimi"&&offer.store!=="maxima"||offer.channel==="online"||isExcludedPorkProduct(offer))continue;const id=offerIdentity(offer),value=comparablePrice(offer);if(!id||value.price==null||value.price<=0)continue;const rows=observations.get(id)??[];rows.push({snapshot:file.slice(0,10),price:value.price,unit:value.unit as UnitType|undefined});observations.set(id,rows)}}return{files,observations}}
const median=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2};
export function summarizeHistory(current:number|undefined,unit:UnitType|undefined,rows:HistoricalObservation[]):HistorySummary{const comparable=rows.filter(row=>row.unit===unit).map(row=>row.price).filter(price=>price>0);if(current==null||comparable.length<MIN_HISTORY_OBSERVATIONS)return{status:"INSUFFICIENT_HISTORY",observations:comparable.length};const low=Math.min(...comparable),high=Math.max(...comparable),middle=median(comparable),status=current<=low?"LOWEST_OBSERVED":current<=low*(1+NEAR_LOW_THRESHOLD)?"NEAR_LOWEST":"NORMAL";return{status,observations:comparable.length,low,median:middle,high,percentBelowMedian:middle>current?Number((((middle-current)/middle)*100).toFixed(1)):0}}
