import {describe,expect,it} from "vitest";
import {deduplicateRimi} from "../scripts/collectors/rimi.js";
import {buildRimiLeafletAudit,collapseLeafletAlternatives,discoverRimiLeafletUrls,mergeRimiSources,parseRimiLeafletPage,parseRimiLeafletViewer,type RimiEshopProduct,type RimiLeaflet} from "../scripts/collectors/rimi-leaflet.js";
import type {RawOffer} from "../scripts/types.js";

const leaflet: RimiLeaflet={leafletId:"weekly-34",title:"Rimi weekly (2026.08.18 - 2026.08.24)",validFrom:"2026-08-18",validUntil:"2026-08-24",sourceUrl:"https://leidiniai.rimi.lt/weekly-34/",pageTexts:[]};
const leafletOffer=(extra:Partial<RawOffer>={}):RawOffer=>({name:"Viščiukų filė RIMI, 500 g",salePrice:2.99,regularPrice:5.49,discountPercent:46,quantity:.5,unit:"kg",pricePerUnit:5.98,pricePerUnitType:"kg",validFrom:leaflet.validFrom,validUntil:leaflet.validUntil,sourceUrl:`${leaflet.sourceUrl}?Page=1`,sourceType:"leaflet",sourcePlatform:"rimi",channel:"physical",publicationId:leaflet.leafletId,promotionSource:"leaflet",promotionActive:true,onlineAvailable:null,physicalStoreAvailability:"unknown",...extra});
const product=(onlineAvailable:boolean):RimiEshopProduct=>({externalId:"sku-500",name:"Viščiukų filė RIMI, 500 g",quantity:.5,unit:"kg",imageUrl:"https://images.rimi/sku-500.jpg",sourceUrl:"https://rimi.lt/produktai/p/sku-500",onlineAvailable,currentPrice:3.49});

describe("Rimi leaflet authority and enrichment",()=>{
  it("keeps leaflet promotion evidence when the e-shop is unavailable and prices conflict",()=>{const result=mergeRimiSources([leafletOffer()],[],[product(false)]);expect(result.offers[0]).toMatchObject({externalId:"sku-500",salePrice:2.99,regularPrice:5.49,discountPercent:46,imageUrl:"https://images.rimi/sku-500.jpg",sourceUrl:"https://rimi.lt/produktai/p/sku-500",leafletSourceUrl:`${leaflet.sourceUrl}?Page=1`,onlineAvailable:false,physicalStoreAvailability:"unknown",ecommercePrice:3.49,promotionSource:"leaflet"});expect(result).toMatchObject({matched:1,unmatched:0,priceConflicts:1})});
  it("retains unmatched leaflet offers with unknown online availability and leaflet imagery",()=>{const result=mergeRimiSources([leafletOffer({imageUrl:"leaflet-crop.jpg"})],[],[]);expect(result.offers[0]).toMatchObject({imageUrl:"leaflet-crop.jpg",onlineAvailable:null,promotionActive:true});expect(result.unmatched).toBe(1)});
  it("retains true online availability without inferring physical stock",()=>expect(mergeRimiSources([leafletOffer()],[],[product(true)]).offers[0]).toMatchObject({onlineAvailable:true,physicalStoreAvailability:"unknown"}));
  it("keeps an e-shop-only promotion",()=>{const online=leafletOffer({externalId:"online",name:"Online milk, 1 l",sourceType:"web",promotionSource:undefined});const result=mergeRimiSources([], [online], []);expect(result.eshopOnly).toBe(1);expect(result.offers[0]).toMatchObject({externalId:"online",promotionSource:"eshop",onlineAvailable:true})});
  it("deduplicates a compatible enriched leaflet promotion without losing leaflet price",()=>{const rows=deduplicateRimi([leafletOffer({externalId:"same"}),leafletOffer({externalId:"same",imageUrl:"eshop.jpg"})]);expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({salePrice:2.99,imageUrl:"eshop.jpg",promotionSource:"leaflet"})});
  it("drops a spurious percent-only alternative when the same leaflet block has a price pair",()=>{const rows=collapseLeafletAlternatives([leafletOffer({externalId:"same",salePrice:undefined,regularPrice:undefined,discountPercent:20}),leafletOffer({externalId:"same",salePrice:2.99,regularPrice:5.49,discountPercent:46})]);expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({salePrice:2.99,regularPrice:5.49,discountPercent:46})});
});

describe("Rimi leaflet discovery, parsing, validity, and coverage",()=>{
  it("discovers multiple leaflet viewers",()=>expect(discoverRimiLeafletUrls(`<div class="sortable-grid__item"><a href="https://leidiniai.rimi.lt/a/"></a></div><div class="sortable-grid__item"><a href="https://leidiniai.rimi.lt/b/"></a></div>`)).toHaveLength(2));
  it("extracts viewer metadata and all embedded page texts",()=>{const html=`<script>window.config={"flipbookTitle":"Rimi (2026.08.18 - 2026.08.24)","pageTexts":["one","two"]}</script>`;expect(parseRimiLeafletViewer(html,"https://leidiniai.rimi.lt/weekly-34/")).toMatchObject({leafletId:"weekly-34",validFrom:"2026-08-18",validUntil:"2026-08-24",pageTexts:["one","two"]})});
  it("parses an identifiable discounted product and preserves leaflet values",()=>{const result=parseRimiLeafletPage("-46% 2,99 5,49 Viščiukų filė be antibiotikų RIMI, 500 g (5,98 € / kg)",1,leaflet);expect(result.offers[0]).toMatchObject({salePrice:2.99,regularPrice:5.49,discountPercent:46,validFrom:"2026-08-18",validUntil:"2026-08-24",promotionSource:"leaflet"})});
  it("associates mixed before/after price layouts with the correct products",()=>{const result=parseRimiLeafletPage("Marškinėliai MYWEAR, 1 vnt. -40% 5,99 9,99 Juodas sijonas MYWEAR, 1 vnt. -40% 9,99 16,99 -40% 11,99 19,99 Juodos kelnės MYWEAR, 1 vnt.",3,leaflet);expect(result.offers).toHaveLength(3);expect(result.offers).toEqual(expect.arrayContaining([expect.objectContaining({name:"Marškinėliai MYWEAR, 1 vnt.",salePrice:5.99}),expect.objectContaining({name:"Juodas sijonas MYWEAR, 1 vnt.",salePrice:9.99}),expect.objectContaining({name:"Juodos kelnės MYWEAR, 1 vnt.",salePrice:11.99})]))});
  it("strips section headings and adjacent price fragments from identities",()=>{const result=parseRimiLeafletPage("IEŠKANTIEMS ŠVIEŽUMO Vaisiai ir daržovės 1,69 1,99 Žaliosios besėklės vynuogės RIMI, 500 g -31% 0,59 0,85 Figos, 1 vnt.",10,leaflet);expect(result.offers.map(item=>item.name)).not.toContain(expect.stringContaining("IEŠKANTIEMS"))});
  it("excludes expired leaflets and reports detected-versus-parsed coverage",()=>{const active={...leaflet,pageTexts:["-46% 2,99 5,49 Viščiukų filė RIMI, 500 g"]},expired={...leaflet,leafletId:"old",validFrom:"2026-08-01",validUntil:"2026-08-10",pageTexts:["-40% 1,00 2,00 Pienas, 1 l"]},audit=buildRimiLeafletAudit([active,expired],"2026-08-24");expect(audit).toMatchObject({activeLeaflets:1,pages:1,detectedBlocks:1,validOffers:1,rejected:0})});
  it("rejects non-product and ambiguous multi-buy blocks without fabricating a price",()=>{const result=parseRimiLeafletPage("Kanceliarinėms prekėms PERKANT 2 VNT. AR DAUGIAU -50%",1,leaflet);expect(result.detected).toBeGreaterThan(0);expect(result.offers).toHaveLength(0);expect(result.rejected).toBeGreaterThan(0)});
});
