import {normalizeName} from "./normalize-name.js";import type {RawOffer,Store} from "../types.js";
export interface CandidateOffer extends RawOffer{store:Store;displayName?:string}
export interface MatchCandidate{rimi:CandidateOffer;maxima:CandidateOffer;score:number;confidence:"HIGH"|"MEDIUM"|"REJECTED";evidence:string[];warnings:string[]}
const stop=new Set("sviez sviezia sviezios liet lietuviskas lietuviski lietuviskos fasuotas fasuota fasuotos rusiu rieb kg g l ml vnt pak ir su be iki klasikinis saldainiai saldainiu sveriami ivairiu".split(" "));
const families:Record<string,string[]>={potato:["bulv"],candy:["saldain","karamel"],ham:["kump"],salmon:["lasis"],herring:["silk"],chicken:["vist","visciuk"],pork:["kiaul"],beef:["jaut"],cheese:["sur"],quark:["varsk"],bread:["duon","baton"],cake:["pyrag","tort"],cookies:["sausain"],oil:["aliej"],pasta:["makaron"],sauce:["padaz"],grapes:["vynuog"],peach:["persik"],paper:["popier"]};
const preparations:Record<string,string[]>={fresh:["sviez","atsald","atves"],frozen:["saldyt"],smoked:["rukyt"],marinated:["marinu","saslyk"],salted:["sudyt"],dried:["vytint","dziovint"],cooked:["virt","kept"]},sensitive=new Set(["candy","cookies","cake"]),brandNoise=new Set(["RIMI","WELL","DONE","XXL","FOOD","STYLE"]);
const subtypes:Record<string,string[]>={breast:["krutin"],thigh:["slaun"],drumstick:["blauzd"],wing:["sparn"],salmon:["lasis"],cod:["menk"],loin:["nugarin"],neck:["sprand"],shoulder:["ment"],pate:["pastet"],sausage:["desr"]};
const words=(name:string)=>normalizeName(name).split(" "),tokenSet=(name:string)=>new Set(words(name).filter(token=>token.length>3&&!stop.has(token)&&!/^\d/.test(token))),tags=(name:string,map:Record<string,string[]>)=>Object.entries(map).filter(([,stems])=>stems.some(stem=>words(name).some(token=>token.startsWith(stem)))).map(([key])=>key),brandTokens=(name:string)=>new Set([...name.matchAll(/(?<![\p{L}\p{N}])[\p{Lu}][\p{Lu}\p{N}&.'’!-]{2,}/gu)].map(match=>match[0]).filter(token=>!brandNoise.has(token))),fat=(name:string)=>{const match=name.match(/(\d+(?:[.,]\d+)?)\s*%\s*(?:rieb|riebumo)?/i);return match?Number(match[1].replace(",",".")):undefined};
export function scoreCandidate(rimi:CandidateOffer,maxima:CandidateOffer):MatchCandidate{const evidence:string[]=[],warnings:string[]=[],a=tokenSet(rimi.name),b=tokenSet(maxima.name),shared=[...a].filter(token=>b.has(token)),aFamily=tags(rimi.name,families),bFamily=tags(maxima.name,families),sharedFamily=aFamily.filter(value=>bFamily.includes(value)),aPrep=tags(rimi.name,preparations),bPrep=tags(maxima.name,preparations),aSubtype=tags(rimi.name,subtypes),bSubtype=tags(maxima.name,subtypes),aFat=fat(rimi.name),bFat=fat(maxima.name),aBrands=brandTokens(rimi.name),bBrands=brandTokens(maxima.name),sharedBrands=[...aBrands].filter(value=>bBrands.has(value));let score=shared.length*8;if(shared.length)evidence.push(`shared Lithuanian tokens: ${shared.join(", ")}`);if(sharedFamily.length){score+=25;evidence.push(`same product family: ${sharedFamily.join(", ")}`)}if(sharedFamily.some(value=>sensitive.has(value))){if(sharedBrands.length>=2){score+=15;evidence.push(`same branded product tokens: ${sharedBrands.join(", ")}`)}else{score-=50;warnings.push("brand-sensitive product identity mismatch")}}if(rimi.pricePerUnitType&&rimi.pricePerUnitType===maxima.pricePerUnitType){score+=10;evidence.push(`compatible unit: ${rimi.pricePerUnitType}`)}else if(rimi.pricePerUnitType!==maxima.pricePerUnitType){score-=100;warnings.push(`unit mismatch: ${rimi.pricePerUnitType??"unknown"} != ${maxima.pricePerUnitType??"unknown"}`)}if(aFamily.length&&bFamily.length&&!sharedFamily.length){score-=40;warnings.push(`product family mismatch: ${aFamily.join("/")} != ${bFamily.join("/")}`)}if(aSubtype.length&&bSubtype.length&&!aSubtype.some(value=>bSubtype.includes(value))){score-=50;warnings.push(`product subtype mismatch: ${aSubtype.join("/")} != ${bSubtype.join("/")}`)}if(aPrep.length&&bPrep.length&&!aPrep.some(value=>bPrep.includes(value))){score-=50;warnings.push(`preparation mismatch: ${aPrep.join("/")} != ${bPrep.join("/")}`)}if(aFat!=null&&bFat!=null&&aFat!==bFat){score-=40;warnings.push(`fat percentage mismatch: ${aFat}% != ${bFat}%`)}const confidence:MatchCandidate["confidence"]=warnings.length?"REJECTED":score>=55?"HIGH":score>=43&&shared.length>=2?"MEDIUM":"REJECTED";return{rimi,maxima,score,confidence,evidence,warnings}}
export function rankCandidates(rimi:CandidateOffer[],maxima:CandidateOffer[]){return rimi.flatMap(a=>maxima.map(b=>scoreCandidate(a,b))).sort((a,b)=>b.score-a.score)}
