import {useMemo,useState} from "react";
import {DealCard} from "../components/DealCard";
import {useDeals} from "../hooks/useDeals";
import {bestGroceryDeals,isGroceryCategory} from "../lib/grocery";
import {retailerPriority} from "../lib/retailer-coverage";
import {matchesDealQuery} from "../lib/search";
import type {Deal,Store} from "../types";

const categories=["All","Groceries","Meat","Fish & Seafood","Dairy & Eggs","Fruit & Vegetables","Bakery","Frozen","Drinks","Snacks","Pantry","Household","Personal Care","Other"];
type Sort="Best Deals"|"Biggest Discount"|"Lowest Price"|"Ending Soon"|"A-Z";
const offers=(deal:Deal,store:"all"|Store)=>deal.offers.filter(offer=>offer.channel!=="online"&&(store==="all"||offer.store===store));
const bestScore=(deal:Deal,store:"all"|Store)=>Math.max(0,...offers(deal,store).map(offer=>offer.intelligence?.dealScore??0));
const biggestDiscount=(deal:Deal,store:"all"|Store)=>Math.max(0,...offers(deal,store).map(offer=>offer.intelligence?.advertisedDiscountPercent??0));
const lowestSale=(deal:Deal,store:"all"|Store)=>Math.min(...offers(deal,store).map(offer=>offer.salePrice??Infinity));
const ending=(deal:Deal,store:"all"|Store)=>offers(deal,store).filter(offer=>offer.validUntil).map(offer=>offer.validUntil!).sort()[0]??"9999-12-31";

export function Home(){
  const{deals,metadata,loading,error}=useDeals(),[q,setQ]=useState(""),[store,setStore]=useState<"all"|Store>("all"),[category,setCategory]=useState("All"),[discount,setDiscount]=useState(0),[soon,setSoon]=useState(false),[sort,setSort]=useState<Sort>("Best Deals"),featured=bestGroceryDeals(deals,8);
  const shown=useMemo(()=>deals.filter(deal=>{const relevant=offers(deal,store);return relevant.length>0&&matchesDealQuery(deal,q)&&(category==="All"||category==="Groceries"&&isGroceryCategory(deal.category)||deal.category===category)&&relevant.some(offer=>(offer.intelligence?.advertisedDiscountPercent??0)>=discount)&&(!soon||relevant.some(offer=>offer.validUntil&&new Date(offer.validUntil).getTime()-Date.now()>=0&&new Date(offer.validUntil).getTime()-Date.now()<3*864e5))}).sort((a,b)=>sort==="A-Z"?a.name.localeCompare(b.name):sort==="Biggest Discount"?biggestDiscount(b,store)-biggestDiscount(a,store):sort==="Lowest Price"?lowestSale(a,store)-lowestSale(b,store):sort==="Ending Soon"?ending(a,store).localeCompare(ending(b,store)):(store==="all"?retailerPriority(a)-retailerPriority(b):0)||bestScore(b,store)-bestScore(a,store)||biggestDiscount(b,store)-biggestDiscount(a,store)||a.name.localeCompare(b.name)),[deals,q,store,category,discount,soon,sort]);
  if(loading)return <div className="state">Loading current deals…</div>;if(error)return <div className="state">We couldn’t load deal data. Try refreshing.</div>;
  return <><section className="dashboard-section first-section"><div className="dashboard-heading"><div><p className="kicker">BEST GROCERY DEALS</p><h2>Food and drink worth a look</h2></div><button className="text-button" onClick={()=>{setCategory("Groceries");document.querySelector("#all-products")?.scrollIntoView({behavior:"smooth"})}}>Browse groceries</button></div>{featured.length?<div className="featured-grid">{featured.map(deal=><DealCard deal={deal} compact key={deal.id}/>)}</div>:<div className="section-empty">No grocery deals are currently available.</div>}</section><section className="dashboard-section" id="all-products"><div className="all-products-head"><div><p className="kicker">BROWSE DEALS</p><h2>All Products</h2></div><label className="search product-search"><span>⌕</span><input value={q} onChange={event=>setQ(event.target.value)} placeholder="Search products…" aria-label="Search all products"/></label>{metadata&&<p className="updated">Updated {new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(metadata.generatedAt))}</p>}</div><div className="toolbar"><div className="store-tabs">{(["all","rimi","maxima"] as const).map(value=><button className={store===value?"active":""} onClick={()=>setStore(value)} key={value}>{value.toUpperCase()}</button>)}</div><div className="selects"><select value={category} onChange={event=>setCategory(event.target.value)} aria-label="Category">{categories.map(value=><option key={value}>{value}</option>)}</select><select value={discount} onChange={event=>setDiscount(+event.target.value)} aria-label="Minimum discount"><option value="0">Any discount</option><option value="20">20%+ off</option><option value="30">30%+ off</option><option value="40">40%+ off</option></select><label><input type="checkbox" checked={soon} onChange={event=>setSoon(event.target.checked)}/> Ending soon</label><select value={sort} onChange={event=>setSort(event.target.value as Sort)} aria-label="Sort deals">{["Best Deals","Biggest Discount","Lowest Price","Ending Soon","A-Z"].map(value=><option key={value}>{value}</option>)}</select></div></div><div className="result-head"><p><strong>{shown.length}</strong> current products</p></div>{shown.length?<main className="grid">{shown.map(deal=><DealCard deal={deal} key={deal.id}/>)}</main>:<div className="state">No current deals found.</div>}</section></>}
