import {Link,useParams} from "react-router-dom";
import {ProductImage} from "../components/ProductImage";
import {useDeals} from "../hooks/useDeals";
import {useShoppingList} from "../hooks/useShoppingList";
import {compareStoreOffers} from "../lib/compare";
import {dateLabel,offerLabel,price,stores} from "../lib/format";
import {RetailerSourceLink} from "../components/RetailerSourceLink";

export function Product(){const{id}=useParams(),{deals,loading}=useDeals(),{add,has}=useShoppingList(),deal=deals.find(item=>item.id===id);if(loading)return <div className="state">Loading deal…</div>;if(!deal)return <div className="state"><h1>Deal not found</h1><Link to="/">Back to deals</Link></div>;const comparison=compareStoreOffers(deal.offers),saved=has(deal);return <main className="product"><Link className="back" to="/">← All deals</Link><p className="eyebrow">{deal.category}{deal.subcategory?` · ${deal.subcategory}`:""}</p><div className="product-title"><h1>{deal.name}</h1><button className="primary-link" disabled={saved} onClick={()=>add(deal)}>{saved?"✓ In shopping list":"+ Add to list"}</button></div><p className="muted">{deal.offers.length} current retailer offer{deal.offers.length===1?"":"s"}. Each image and price comes from that retailer’s promotion.</p><div className="offer-list">{deal.offers.map((offer,index)=><article className="offer retailer-offer" key={`${offer.store}-${offer.channel}-${offer.sourceName}-${index}`}><ProductImage src={offer.imageUrl} alt={`${deal.name} at ${offerLabel(offer)}`} className="offer-image"/><div className="offer-content"><header><span className="store" style={{color:stores[offer.store].color}}>{offerLabel(offer)}</span>{comparison.winner===offer.store&&<span className="best-pill">CHEAPEST TRACKED</span>}</header><div className="offer-price">{price(offer)}</div>{offer.regularPrice&&<p>Regular price €{offer.regularPrice.toFixed(2)} {offer.intelligence?.advertisedDiscountPercent!=null&&<strong className="discount">−{offer.intelligence.advertisedDiscountPercent}%</strong>}</p>}{offer.intelligence?.reasons.includes("LOYALTY_REQUIRED")&&<p><strong>Loyalty card required</strong></p>}{offer.promotionConditions&&<p><strong>{offer.promotionConditions}</strong></p>}<p className="source-name">{offer.promotionSource==="leaflet"?"Advertised in current Rimi leaflet":`Source: ${offerLabel(offer)}`}</p>{offer.promotionSource==="leaflet"&&<p className="availability-note">{offer.onlineAvailable===true?"Available in Rimi e-shop":offer.onlineAvailable===false?"Online shop: currently unavailable":"Online availability unknown"}<br/>Availability may vary by store</p>}<p>{offer.validUntil?`Valid until ${dateLabel(offer.validUntil)}`:"Current while stocks last"}</p><RetailerSourceLink offer={offer} productName={deal.name}/>{offer.leafletSourceUrl&&offer.leafletSourceUrl!==offer.sourceUrl&&<><br/><a href={offer.leafletSourceUrl} target="_blank" rel="noopener noreferrer">View Rimi leaflet →</a></>}</div></article>)}</div></main>}
