import {Link} from "react-router-dom";
import {useShoppingList} from "../hooks/useShoppingList.js";
import {compareStoreOffers} from "../lib/compare.js";
import {price,stores} from "../lib/format.js";
import {compactRetailerOffers,regularPriceLabel} from "../lib/retailer-coverage.js";
import type {Deal,Offer} from "../types/index.js";
import {ProductImage} from "./ProductImage.js";

const badge=(offer:Offer)=>offer.intelligence?.historicalStatus==="LOWEST_OBSERVED"?"Lowest observed":offer.intelligence?.historicalStatus==="NEAR_LOWEST"?"Near historical low":(offer.intelligence?.advertisedDiscountPercent??0)>=40?"Great Deal":(offer.intelligence?.advertisedDiscountPercent??0)>=25?"Good Deal":undefined;
export function DealCard({deal,compact=false}:{deal:Deal;compact?:boolean}){const{add,has}=useShoppingList(),saved=has(deal),offers=compactRetailerOffers(deal),primary=[...offers].sort((a,b)=>(b.intelligence?.dealScore??0)-(a.intelligence?.dealScore??0)||a.store.localeCompare(b.store))[0],comparison=compareStoreOffers(offers),label=badge(primary);return <article className={`deal-card ${compact?"compact":""}`}><Link to={`/products/${deal.id}`} className="deal-card-link"><ProductImage src={deal.primaryImageUrl} alt={deal.name} className="card-image"/><div className="card-top"><div><span className="eyebrow">{deal.category}</span><h2>{deal.name}</h2></div></div><div className="deal-badges">{label&&<span className="deal-badge">{label}</span>}{primary.intelligence?.advertisedDiscountPercent!=null&&<span className="discount-badge">−{primary.intelligence.advertisedDiscountPercent}%</span>}</div><div className="card-retailer-prices">{offers.map(offer=>{const regular=regularPriceLabel(offer);return <div className={`card-retailer-price ${comparison.winner===offer.store?"lowest":""}`} key={offer.store}><span className="store" style={{color:stores[offer.store].color}}>{stores[offer.store].label}</span><strong>{price(offer)}</strong>{regular&&<small>{regular}</small>}</div>})}</div></Link><button className="add-list" disabled={saved} onClick={()=>add(deal)} aria-label={saved?`${deal.name} is in your shopping list`:`Add ${deal.name} to shopping list`}>{saved?"✓ In list":"+ Add to list"}</button></article>}
