import {mkdir,readFile,writeFile} from "node:fs/promises";
import {buildDeals,isActive} from "./build-deals.js";
import {groupingMetrics} from "./normalization/audit-metrics.js";
import {rankCandidates,type CandidateOffer} from "./normalization/candidate-matches.js";
import {normalizeName} from "./normalization/normalize-name.js";
import {translateProductName} from "./translation/translate-product.js";
import type {StoreData} from "./types.js";

const keys=["rimi","maxima","barbora"],inputs:StoreData[]=[];
for(const key of keys)try{inputs.push(JSON.parse(await readFile(`data/current/${key}.json`,"utf8")) as StoreData)}catch{/* optional source */}
const active=inputs.flatMap(data=>data.offers.filter(offer=>isActive(offer)).map(offer=>({data,offer,translation:translateProductName(offer.name,offer.brand)})));
const count=(source:"CANONICAL"|"AUTO"|"UNTRANSLATED",rows=active)=>rows.filter(row=>row.translation.source===source).length;
const canonical=count("CANONICAL"),automatic=count("AUTO"),untranslated=count("UNTRANSLATED"),coverage=(canonical+automatic)/(active.length||1),deals=buildDeals(inputs),grouping=groupingMetrics(deals);
const byStore=inputs.map(data=>{const rows=active.filter(row=>row.data===data),canonical=count("CANONICAL",rows),automatic=count("AUTO",rows),untranslated=count("UNTRANSLATED",rows);return{store:data.offers[0]?.sourcePlatform??data.store,total:rows.length,canonical,automatic,untranslated,coverage:(canonical+automatic)/(rows.length||1)}});
const autoNames=new Map<string,string[]>();for(const row of active.filter(row=>row.translation.source==="AUTO")){const names=autoNames.get(row.translation.displayName)??[];names.push(row.offer.name);autoNames.set(row.translation.displayName,names)}
const autoNameCollisions=[...autoNames].filter(([,names])=>new Set(names).size>1).map(([displayName,names])=>({displayName,sourceNames:[...new Set(names)]}));
const warnings=deals.flatMap(deal=>{const units=new Set(deal.offers.map(offer=>offer.pricePerUnitType).filter(Boolean)),prices=deal.offers.map(offer=>offer.pricePerUnit).filter((price):price is number=>price!=null),ratio=prices.length>1?Math.max(...prices)/Math.min(...prices):1,reasons=[units.size>1?`incompatible units: ${[...units].join(", ")}`:"",ratio>5?`unit-price ratio ${ratio.toFixed(1)}x`:""].filter(Boolean);return reasons.length?[{id:deal.id,displayName:deal.name,reasons}]:[]});
const records=active.filter(row=>row.translation.source==="UNTRANSLATED").map(({data,offer,translation})=>({sourceName:offer.name,normalizedName:normalizeName(offer.name),store:data.store,sourcePlatform:offer.sourcePlatform,category:offer.category??offer.sourceCategory??"Other",brand:offer.brand,quantity:offer.quantity,unit:offer.unit,price:offer.salePrice,pricePerUnit:offer.pricePerUnit,unknownTokens:translation.unknownTokens,confidence:translation.confidence}));
const suggestions:{a:string;aStore:string;b:string;bStore:string;sharedTokens:string[]}[]=[];
const summary={activeOffers:active.length,canonical,automatic,untranslated,englishCoveragePercent:Number((coverage*100).toFixed(1)),canonicalUngrouped:active.length-canonical,normalizedProducts:deals.length,...grouping,autoNameCollisions:autoNameCollisions.length,warnings:warnings.length};
const physicalDeals=deals.map(deal=>({...deal,offers:deal.offers.filter(offer=>offer.channel!=="online")})).filter(deal=>deal.offers.length),rimiOnly=physicalDeals.filter(deal=>deal.offers.every(offer=>offer.store==="rimi")).length,maximaOnly=physicalDeals.filter(deal=>deal.offers.every(offer=>offer.store==="maxima")).length,crossDeals=physicalDeals.filter(deal=>new Set(deal.offers.map(offer=>offer.store)).size===2),crossOffers=crossDeals.reduce((total,deal)=>total+deal.offers.length,0),unmatchedDeals=physicalDeals.filter(deal=>deal.id.startsWith("unmatched-")),candidateRows=rankCandidates(unmatchedDeals.flatMap(deal=>deal.offers.filter(offer=>offer.store==="rimi").map(offer=>({...offer,displayName:deal.name} as CandidateOffer))),unmatchedDeals.flatMap(deal=>deal.offers.filter(offer=>offer.store==="maxima").map(offer=>({...offer,displayName:deal.name} as CandidateOffer)))),highCandidates=candidateRows.filter(row=>row.confidence==="HIGH"),mediumCandidates=candidateRows.filter(row=>row.confidence==="MEDIUM"),rejectedConflicts=candidateRows.filter(row=>row.confidence==="REJECTED"&&row.warnings.length&&row.score>=0);

console.log(`NORMALIZATION / TRANSLATION AUDIT\n\nActive offers: ${summary.activeOffers}\n\nDisplay names:\nCanonical: ${canonical}\nAutomatic: ${automatic}\nUntranslated: ${untranslated}\nEnglish coverage: ${summary.englishCoveragePercent.toFixed(1)}%\n\nBy store:`);for(const row of byStore)console.log(`${row.store}: canonical ${row.canonical}, automatic ${row.automatic}, untranslated ${row.untranslated} / ${row.total} (${(row.coverage*100).toFixed(1)}%)`);
console.log(`\nProduct grouping:\nNormalized products: ${summary.normalizedProducts}\nSingle-store: ${grouping.singleStore}\nTwo-store: ${grouping.twoStore}\nCross-store offer groups: ${grouping.crossStoreGroups}\nRimi ↔ Maxima: ${grouping.rimiMaxima}\nAUTO-name collisions (never auto-grouped): ${summary.autoNameCollisions}\nSuspicious groups: ${summary.warnings}`);
console.log(`\nRIMI ↔ MAXIMA MATCHING\nRimi offers: ${active.filter(row=>row.data.store==="rimi").length}\nMaxima physical offers: ${active.filter(row=>row.data.store==="maxima"&&row.offer.channel!=="online").length}\nRimi-only products: ${rimiOnly}\nMaxima-only products: ${maximaOnly}\nRimi + Maxima products: ${crossDeals.length}\nCross-store offer coverage: ${crossOffers}/${active.length} offers (${((crossOffers/active.length)*100).toFixed(1)}%)\nHigh-confidence unmatched candidates: ${highCandidates.length}\nMedium-confidence candidates: ${mediumCandidates.length}\nRejected due to attribute mismatch: ${rejectedConflicts.length}`);
for(const candidate of [...highCandidates,...mediumCandidates].slice(0,20))console.log(`\n${candidate.confidence} CANDIDATE — score ${candidate.score}\nRIMI: ${candidate.rimi.name}\n  display: ${candidate.rimi.displayName} | unit: ${candidate.rimi.pricePerUnitType??"unknown"} | €${candidate.rimi.pricePerUnit??candidate.rimi.salePrice??"?"}\nMAXIMA: ${candidate.maxima.name}\n  display: ${candidate.maxima.displayName} | unit: ${candidate.maxima.pricePerUnitType??"unknown"} | €${candidate.maxima.pricePerUnit??candidate.maxima.salePrice??"?"}\nEvidence: ${candidate.evidence.join("; ")||"none"}\nWarnings: ${candidate.warnings.join("; ")||"none"}`);
for(const candidate of rejectedConflicts.slice(0,10))console.log(`\nNOT MATCHED\nRIMI: ${candidate.rimi.name}\nMAXIMA: ${candidate.maxima.name}\nReason: ${candidate.warnings.join("; ")}`);
console.log("\nUnmatched products (first 12 per store/category):");const buckets=new Map<string,typeof records>();for(const record of records){const key=`${record.store} / ${record.category}`,bucket=buckets.get(key)??[];bucket.push(record);buckets.set(key,bucket)}for(const [label,rows] of [...buckets].sort(([a],[b])=>a.localeCompare(b)))console.log(`\n${label}\n${rows.slice(0,12).map(row=>`- ${row.sourceName} [unknown: ${row.unknownTokens.join(", ")}]`).join("\n")}`);
if(suggestions.length){console.log("\nSuggested matches (audit only):");for(const item of suggestions)console.log(`- ${item.aStore}: ${item.a}\n  ${item.bStore}: ${item.b}\n  shared: ${item.sharedTokens.join(", ")}`)}if(warnings.length){console.log("\nSuspicious groups:");for(const warning of warnings)console.log(`- ${warning.id}: ${warning.reasons.join("; ")}`)}
if(process.argv.includes("--json")){await mkdir("debug/normalization",{recursive:true});await writeFile("debug/normalization/report.json",`${JSON.stringify({summary:{...summary,rimiOnly,maximaOnly,crossStoreOffers:crossOffers,crossStoreOfferCoveragePercent:Number(((crossOffers/active.length)*100).toFixed(1)),highConfidenceCandidates:highCandidates.length,mediumConfidenceCandidates:mediumCandidates.length,rejectedAttributeConflicts:rejectedConflicts.length},byStore,untranslated:records,candidates:{high:highCandidates,medium:mediumCandidates,rejected:rejectedConflicts},suggestions,autoNameCollisions,warnings},null,2)}\n`);console.log("\nWrote debug/normalization/report.json")}
