import {readFile} from "node:fs/promises";
import {loadHistory,MIN_HISTORY_OBSERVATIONS} from "./deals/history.js";
import type {BestDealsData} from "./deals/types.js";
import type {Deal} from "./types.js";

const deals=JSON.parse(await readFile("data/current/deals.json","utf8")) as Deal[],ranking=JSON.parse(await readFile("data/current/best-deals.json","utf8")) as BestDealsData,offers=deals.flatMap(deal=>deal.offers).filter(offer=>offer.channel!=="online"),history=await loadHistory();
const withRegular=offers.filter(offer=>offer.regularPrice!=null).length,withDiscount=offers.filter(offer=>offer.intelligence?.advertisedDiscountPercent!=null).length,withUnit=offers.filter(offer=>offer.pricePerUnit!=null&&offer.pricePerUnitType).length,sufficient=offers.filter(offer=>(offer.intelligence?.historicalObservations??0)>=MIN_HISTORY_OBSERVATIONS).length,insufficient=offers.filter(offer=>offer.intelligence?.historicalStatus==="INSUFFICIENT_HISTORY").length;
const anomalies=offers.flatMap(offer=>{const intel=offer.intelligence,reasons=[intel?.advertisedDiscountPercent!=null&&intel.advertisedDiscountPercent>90?">90% discount":"",offer.regularPrice!=null&&offer.salePrice!=null&&offer.salePrice>=offer.regularPrice?"sale price >= regular price":"",intel?.absoluteSaving!=null&&intel.absoluteSaving<0?"negative saving":"",intel?.historicalMedian!=null&&(offer.pricePerUnit??offer.salePrice??0)>intel.historicalMedian*10?"current price >10x historical median":""].filter(Boolean);return reasons.length?[{offer:offer.sourceName,store:offer.store,reasons}]:[]});
console.log(`DEAL INTELLIGENCE AUDIT\n\nActive physical offers: ${offers.length}\nWith regular price: ${withRegular}\nWith advertised discount: ${withDiscount}\nWith normalized unit price: ${withUnit}\nWith comparable history (>=${MIN_HISTORY_OBSERVATIONS}): ${sufficient}\nInsufficient history: ${insufficient}\n\nHistory snapshots: ${history.files.length}\nEarliest: ${history.files[0]?.slice(0,10)??"none"}\nLatest: ${history.files.at(-1)?.slice(0,10)??"none"}\n\nTop 20:`);
for(const row of ranking.all.slice(0,20))console.log(`${row.rank}. ${row.product} | ${row.store.toUpperCase()} | €${row.salePrice??"?"} | was €${row.regularPrice??"?"} | ${row.discountPercent??"?"}% | score ${row.dealScore} | ${row.reasons.join(", ")}`);
console.log(`\nPotential anomalies: ${anomalies.length}`);for(const anomaly of anomalies)console.log(`- ${anomaly.store}: ${anomaly.offer} — ${anomaly.reasons.join(", ")}`);
