import {readFile,writeFile} from "node:fs/promises";
import {generateDealIntelligence} from "./deals/write-ranking.js";
import {isExcludedPorkProduct} from "./exclusions/pork.js";
import {matchProduct} from "./normalization/match-product.js";
import {slugify} from "./normalization/normalize-name.js";
import {selectPrimaryImage} from "./normalization/product-images.js";
import {translateProductName,translationStats} from "./translation/translate-product.js";
import type {Deal,DealOffer,Store,StoreData} from "./types.js";

const stores:Store[]=["rimi","maxima"];
export function isActive(o:{validFrom?:string;validUntil?:string},today=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Vilnius"}).format(new Date())){return(!o.validFrom||o.validFrom<=today)&&(!o.validUntil||o.validUntil>=today)}
export function buildDeals(inputs:StoreData[],today?:string):Deal[]{const map=new Map<string,Deal>();for(const data of inputs)for(const raw of data.offers.filter(o=>isActive(o,today)&&!isExcludedPorkProduct(o))){const alias=matchProduct(raw.name),translation=translateProductName(raw.name,raw.brand),key=alias?.id??`unmatched-${slugify(raw.name)}`,deal=map.get(key)??{id:key,name:translation.displayName,category:alias?.category??translation.category??raw.category??"Other",subcategory:alias?.subcategory,aliases:alias?.aliases??[],offers:[]},sourcePlatform=raw.sourcePlatform??data.store,offer:DealOffer={...raw,sourcePlatform,channel:raw.channel??(sourcePlatform==="barbora"?"online":"physical"),store:data.store,sourceName:raw.name,displayName:translation.displayName,displayNameSource:translation.source,canonicalProductId:translation.canonicalProductId};deal.offers.push(offer);map.set(key,deal)}return[...map.values()].map(d=>({...d,primaryImageUrl:selectPrimaryImage(d.offers),offers:d.offers.sort((a,b)=>a.pricePerUnitType===b.pricePerUnitType?(a.pricePerUnit??a.salePrice??Infinity)-(b.pricePerUnit??b.salePrice??Infinity):a.store.localeCompare(b.store))})).sort((a,b)=>a.name.localeCompare(b.name))}
async function main(){const inputs=await Promise.all(stores.map(async store=>JSON.parse(await readFile(`data/current/${store}.json`,"utf8")) as StoreData));try{inputs.push(JSON.parse(await readFile("data/current/barbora.json","utf8")) as StoreData)}catch{/* optional source */}const active=inputs.flatMap(data=>data.offers).filter(offer=>!isExcludedPorkProduct(offer)),deals=buildDeals(inputs),translation=translationStats(active),generatedAt=new Date().toISOString();await generateDealIntelligence(deals,generatedAt);try{const metadata=JSON.parse(await readFile("data/current/metadata.json","utf8")),storeEntries=inputs.map(data=>{const key=data.offers[0]?.sourcePlatform==="barbora"?"barbora":data.store;return[key,{status:"retained",offers:data.offers.filter(offer=>!isExcludedPorkProduct(offer)).length}]});await writeFile("data/current/metadata.json",`${JSON.stringify({...metadata,generatedAt,stores:Object.fromEntries(storeEntries),totalOffers:active.length,normalizedProducts:deals.length,translation},null,2)}\n`)}catch{/* metadata created by collection */}}
if(process.argv[1]?.endsWith("build-deals.ts"))main().catch(e=>{console.error(e);process.exitCode=1});
