import {matchExactTranslation,matchProduct} from "../normalization/match-product.js";import {normalizeName} from "../normalization/normalize-name.js";import {ignored,phrases,vocabulary} from "./vocabulary.js";import type {TranslationResult} from "./types.js";
const cache=new Map<string,TranslationResult>(),quantity=/\b\d+(?:[.,]\d+)?\s*(?:x\s*\d+(?:[.,]\d+)?\s*)?(?:kg|g|l|ml|vnt\.?|pcs|pak\.?)\b/gi,promo=/\b(?:AKCIJA|SUPER KAINA|TIK SU AČIŪ KORTELE|NAUJIENA)\b|[-−]\d+%/gi;
const title=(words:string[])=>words.flatMap(word=>word.split(" ")).map(word=>/^[\p{Lu}0-9&.'’!-]{2,}$/u.test(word)?word:word.split("-").map(part=>part.charAt(0).toUpperCase()+part.slice(1).toLowerCase()).join("-")).join(" ").replace(/\bWith\b/g,"with").replace(/\bAnd\b/g,"and");
export function translateProductName(sourceName:string,brand?:string):TranslationResult{const key=`${sourceName}|${brand??""}`,cached=cache.get(key);if(cached)return cached;const canonical=matchProduct(sourceName);if(canonical){const result={displayName:canonical.name,source:"CANONICAL" as const,confidence:1,unknownTokens:[],category:canonical.category,canonicalProductId:canonical.id};cache.set(key,result);return result}const known=matchExactTranslation(sourceName);if(known){const result={displayName:known.name,source:"AUTO" as const,confidence:1,unknownTokens:[],category:known.category};cache.set(key,result);return result}
 const cleaned=sourceName.replace(promo," ").replace(quantity," ").replace(/\b\d+(?:[.,]\d+)?\s*%\b/g," ").replace(/[€~=/]/g," ").replace(/\s+/g," ").trim(),normalized=normalizeName(cleaned),brands=[...cleaned.matchAll(/(?<![\p{L}\p{N}])[\p{Lu}][\p{Lu}\p{N}&.'’!-]{2,}/gu)].map(match=>match[0]).filter(word=>!vocabulary[normalizeName(word)]),tokens=normalized.split(" ").filter(Boolean),translated:string[]=[];let understood=0;const unknown:string[]=[];
 for(let index=0;index<tokens.length;){let hit=false;for(const size of [4,3,2]){const phrase=tokens.slice(index,index+size).join(" "),english=phrases.get(phrase);if(english){translated.push(english);understood+=size;index+=size;hit=true;break}}if(hit)continue;const token=tokens[index++];if(ignored.has(token)||/^\d+$/.test(token))continue;const english=vocabulary[token];if(english){translated.push(english);understood++}else if(!brands.some(value=>normalizeName(value)===token))unknown.push(token)}
 const meaningful=understood+unknown.length,confidence=meaningful?understood/meaningful:0;if(understood<2||confidence<.67){const result={displayName:sourceName,source:"UNTRANSLATED" as const,confidence,unknownTokens:[...new Set(unknown)]};cache.set(key,result);return result}const words=[...(brand?[brand]:brands),...translated.filter((word,index,array)=>array.indexOf(word)===index)],result={displayName:title(words),source:"AUTO" as const,confidence,unknownTokens:[...new Set(unknown)]};cache.set(key,result);return result}
export function clearTranslationCache(){cache.clear()}
export function translationStats(offers:{name:string;brand?:string}[]){const values=offers.map(offer=>translateProductName(offer.name,offer.brand)),canonical=values.filter(value=>value.source==="CANONICAL").length,automatic=values.filter(value=>value.source==="AUTO").length,untranslated=values.length-canonical-automatic;return{totalOffers:values.length,canonical,automatic,untranslated,englishCoveragePercent:values.length?Number((((canonical+automatic)/values.length)*100).toFixed(1)):0}}
