export const phrases=new Map<string,string>([
 ["vistienos krutineles file","Chicken Breast"],["malta jautiena","Ground Beef"],["graikiskas jogurtas","Greek Yogurt"],["alyvuogiu aliejus","Olive Oil"],["tualetinis popierius","Toilet Paper"],["popieriniai ranksluosciai","Paper Towels"],["indu ploviklis","Dishwashing Liquid"],["be laktozes","Lactose-Free"],["be cukraus","Sugar-Free"],["saltai rukyta","Cold-Smoked"],["karstai rukyta","Hot-Smoked"],["pirmo spaudimo","Extra Virgin"],["pomidoru padazas","Tomato Sauce"],["mineralinis vanduo","Mineral Water"],["energinis gerimas","Energy Drink"],["gaivusis gerimas","Soft Drink"],["braskiu skonio","Strawberry"],["avieciu skonio","Raspberry"],["vaniles skonio","Vanilla"],["sokolado skonio","Chocolate"]
]);
export const vocabulary:Record<string,string>={
 sviezias:"Fresh",sviezia:"Fresh",sviezios:"Fresh",saldytas:"Frozen",saldyta:"Frozen",saldytos:"Frozen",rukytas:"Smoked",rukyta:"Smoked",rukytos:"Smoked",marinuotas:"Marinated",marinuota:"Marinated",ekologiskas:"Organic",ekologiska:"Organic",naturalus:"Natural",naturali:"Natural",
 vistiena:"Chicken",vistienos:"Chicken",visciuku:"Chicken",kiauliena:"Pork",kiaulienos:"Pork",jautiena:"Beef",jautienos:"Beef",kalakutiena:"Turkey",kalakutienos:"Turkey",krutinele:"Breast",krutineles:"Breast",slaunele:"Thigh",slauneles:"Thighs",sparneliai:"Wings",file:"Fillet",farsas:"Ground Meat",kumpis:"Ham",sonine:"Bacon",desra:"Sausage",desreles:"Sausages",
 lasisa:"Salmon",lasisos:"Salmon",menke:"Cod",menkiu:"Cod",silke:"Herring",silkes:"Herring",tunas:"Tuna",tuno:"Tuna",zuvies:"Fish",ikrai:"Roe",
 pienas:"Milk",sviestas:"Butter",jogurtas:"Yogurt",suris:"Cheese",surio:"Cheese",grietine:"Sour Cream",grietinele:"Cream",varske:"Quark",kiausiniai:"Eggs",kefyras:"Kefir",
 obuoliai:"Apples",bananai:"Bananas",apelsinai:"Oranges",arbuzai:"Watermelon",bulves:"Potatoes",pomidorai:"Tomatoes",agurkai:"Cucumbers",svogunai:"Onions",morkos:"Carrots",kopustai:"Cabbage",citrinos:"Lemons",vynuoges:"Grapes",persikai:"Peaches",nektarinai:"Nectarines",slyvos:"Plums",grybai:"Mushrooms",
 ryziai:"Rice",makaronai:"Pasta",miltai:"Flour",cukrus:"Sugar",druska:"Salt",aliejus:"Oil",kava:"Coffee",arbata:"Tea",pupeles:"Beans",lesiai:"Lentils",grikiai:"Buckwheat",grikiu:"Buckwheat",kruopos:"Groats",majonezas:"Mayonnaise",padazas:"Sauce",
 lietuviskos:"Lithuanian",lietuviski:"Lithuanian",braskes:"Strawberries",pievagrybiai:"Mushrooms",broileriu:"Broiler",blauzdeles:"Drumsticks",brandintas:"Aged",brandinti:"Aged",nugarines:"Sirloin",antrekoto:"Ribeye",kepsnys:"Steak",mentes:"Shoulder",kumpio:"Ham",saslykas:"Shashlik",cesnakais:"Garlic",pjaustyta:"Sliced",pjaustytas:"Sliced",vytintas:"Dry-Cured",vytinta:"Dry-Cured",lazdeles:"Sticks",keptas:"Cooked",pastetas:"Pate",kietasis:"Hard",lydytas:"Processed",tepamasis:"Spread",surelis:"Cheese Snack",glaistytas:"Coated",batoneliu:"Bars",rinkinys:"Pack",saldainiai:"Candy",guminukai:"Gummies",sausainiai:"Cookies",riestainiai:"Bagels",dribsniai:"Cereal",uogiene:"Jam",kecupas:"Ketchup",prieskoniu:"Seasoning",misinys:"Mix",saulegrazu:"Sunflower",pomidoru:"Tomato",sultys:"Juice",granatu:"Pomegranate",gazuotas:"Carbonated",nealkoholinis:"Non-Alcoholic",alus:"Beer",energinis:"Energy",gerimas:"Drink",mineralinis:"Mineral",vanduo:"Water",putojanti:"Sparkling",zalioji:"Green",konservuotas:"Canned",sausas:"Dry",kaciu:"Cat",edalas:"Food",kraikas:"Litter",skanestas:"Treat",pica:"Pizza",ledai:"Ice Cream",plombyras:"Ice Cream",krevetes:"Shrimp",tunu:"Tuna",pjausniai:"Steaks",silkiu:"Herring",sudyta:"Salted",oda:"Skin",kruasanas:"Croissant",batonas:"Baguette",paklotai:"Underpads",vatos:"Cotton",lapeliai:"Pads",higieniniai:"Sanitary",paketai:"Pads",iklotai:"Liners",prezervatyvai:"Condoms",veido:"Face",dieninis:"Day",naktinis:"Night",
 skalbiklis:"Laundry Detergent",popierius:"Paper",ranksluosciai:"Towels",maisai:"Bags",sluostes:"Wipes",sampunas:"Shampoo",kremas:"Cream",
 braskiu:"Strawberry",vaniles:"Vanilla",sokolado:"Chocolate",avieciu:"Raspberry",citrinu:"Lemon",skonio:"Flavoured",su:"with",ir:"and"
};
export const ignored=new Set(["rieb","riebumo","ivairiu","rusiu","ieskoti","saldytuve","gryn","kiekio","akcija","naujiena","super","kaina","tik","kortele","fasuotas","fasuotos","pak","dez","ind","skard","but","rit","sluoksniu","lapeliu","dydis","men","kompl","rink","vnt","a","r","s","m","d"]);
