import * as cheerio from "cheerio";
import {parsePrice} from "../normalization/normalize-price.js";
import {normalizeName} from "../normalization/normalize-name.js";
import {parseQuantity,unitPrice} from "../normalization/normalize-units.js";
import {retainNonPorkOffer} from "../exclusions/pork.js";
import type {RawOffer} from "../types.js";

export const RIMI_LEAFLETS_URL="https://www.rimi.lt/asortimentas/rimi-savaitinis-leidinys";
export interface RimiLeaflet{leafletId:string;title:string;validFrom:string;validUntil:string;sourceUrl:string;pageTexts:string[]}
export interface RimiLeafletAudit{activeLeaflets:number;pages:number;detectedBlocks:number;parsedBlocks:number;validOffers:number;rejected:number;rejections:Record<string,number>;offers:RawOffer[]}
export interface RimiEshopProduct{externalId:string;name:string;brand?:string;quantity?:number;unit?:string;imageUrl?:string;sourceUrl:string;onlineAvailable:boolean;currentPrice?:number}
const clean=(value:string)=>value.replace(/\s+/g," ").trim();
const jsonArrayAfter=(source:string,key:string):unknown[]=>{const start=source.indexOf(`"${key}":`);if(start<0)return[];const open=source.indexOf("[",start);if(open<0)return[];let depth=0,string=false,escape=false;for(let i=open;i<source.length;i++){const char=source[i];if(string){if(escape)escape=false;else if(char==="\\")escape=true;else if(char==='"')string=false;continue}if(char==='"'){string=true;continue}if(char==="[")depth++;if(char==="]"&&--depth===0)return JSON.parse(source.slice(open,i+1)) as unknown[]}return[]};
const iso=(year:string,month:string,day:string)=>`${year}-${month.padStart(2,"0")}-${day.padStart(2,"0")}`;
export function parseLeafletValidity(title:string){const match=title.match(/(20\d{2})[.-](\d{1,2})[.-](\d{1,2})\s*[-–]\s*(20\d{2})[.-](\d{1,2})[.-](\d{1,2})/);return match?{validFrom:iso(match[1],match[2],match[3]),validUntil:iso(match[4],match[5],match[6])}:undefined}
export function parseRimiLeafletViewer(html:string,sourceUrl:string):RimiLeaflet|undefined{const title=(html.match(/"flipbookTitle":"((?:\\.|[^"\\])*)"/)?.[1]);if(!title)return;const decoded=JSON.parse(`"${title}"`) as string,validity=parseLeafletValidity(decoded);if(!validity)return;const pageTexts=jsonArrayAfter(html,"pageTexts").map(String);if(!pageTexts.length)return;return{leafletId:new URL(sourceUrl).pathname.split("/").filter(Boolean).at(-1)!,title:decoded,...validity,sourceUrl,pageTexts}}
export function discoverRimiLeafletUrls(html:string){const $=cheerio.load(html),urls=new Set<string>();$(".sortable-grid__item a[href*='leidiniai.rimi.lt']").each((_,element)=>{const href=$(element).attr("href");if(href)urls.add(new URL(href,RIMI_LEAFLETS_URL).href)});return[...urls]}
const noise=/^(?:RIMI|PASIŪLYMAI|ATGAL Į MOKYKLĄ|MĖGSTANTIEMS|KANCELIARIN|NUOLAIDA|PERKANT|IKI|TIK|GERA KAINA)/i;
function trimName(value:string){return clean(value).replace(/^\d{5,8}(?:\s+\d{5,8})*\s+/,"").replace(/^KIEKVIENAI DIENAI(?:\s+Paruoštas maistas|\s+Švieži kepiniai)?\s+/i,"").replace(/^IEŠKANTIEMS ŠVIEŽUMO\s+Vaisiai ir daržovės\s+\d+[,.]\d{2}\s+\d+[,.]\d{2}\s+/i,"").replace(/^[a-ząčęėįšųūž][\s\S]{0,90}?\d+[,.]\d{2}\s+(?=[A-ZĄČĘĖĮŠŲŪŽ])/i,"").replace(/^(?:(?:kg|l|vnt\.?)|[^)]{1,45})\)\s*\d+[,.]\d+\s*(?:TIK\s*)?/i,"").replace(/^(?:[^a-ząčęėįšųūž]*\s+){0,3}/i,"").trim()}
function offer(name:string,salePrice:number|undefined,regularPrice:number|undefined,discountPercent:number|undefined,leaflet:RimiLeaflet,page:number,conditions?:string):RawOffer|undefined{const finalName=trimName(name),quantity=parseQuantity(finalName),leafletSourceUrl=`${leaflet.sourceUrl}?Page=${page}`;if(finalName.length<4||noise.test(finalName)||!/[A-ZĄČĘĖĮŠŲŪŽ]/.test(finalName[0]))return;return{name:finalName,salePrice,regularPrice,discountPercent,quantity:quantity?.quantity,unit:quantity?.unit,pricePerUnit:salePrice!=null?unitPrice(salePrice,quantity):undefined,pricePerUnitType:quantity?.type,validFrom:leaflet.validFrom,validUntil:leaflet.validUntil,sourceUrl:leafletSourceUrl,leafletSourceUrl,promotionType:/MANO RIMI|KORTELE/i.test(conditions??"")?"LOYALTY":conditions?"CAMPAIGN":"SALE",sourceType:"leaflet",sourcePlatform:"rimi",channel:"physical",publicationId:leaflet.leafletId,leafletTitle:leaflet.title,promotionSource:"leaflet",promotionActive:true,promotionConditions:conditions,onlineAvailable:null,physicalStoreAvailability:"unknown",page,confidence:"HIGH"}}
const productFragment=/([A-Za-zĄČĘĖĮŠŲŪŽąčęėįšųūž][\s\S]{2,190}?(?:(?:\d+(?:[,.]\d+)?\s*(?:kg|g|l|ml|vnt\.?))|(?:\(\d+\s*rūš(?:is|ys|ių)\))))/gi;
function candidate(segment:string,position:"first"|"last"){const prepared=segment.replace(/Nuolaida netaikoma[\s\S]*/i,"").replace(/Pasiūlymas galioja\s+20\d{2}\s+\d{1,2}\s+\d{1,2}\s*[-—–]\s*(?:20\d{2}\s+)?\d{1,2}\s+\d{1,2}/gi," ").replace(/\b(?:H|TIK|IKI)\b/gi," "),matches=[...prepared.matchAll(productFragment)].map(match=>trimName(match[1])).filter(value=>value.length>=4&&!noise.test(value));return position==="first"?matches[0]:matches.at(-1)}
function condition(text:string){return text.match(/(?:PERKANT\s+\d+\s+VNT\.?\s+AR\s+DAUGIAU|\d+\s*\+\s*\d+|MANO RIMI[^.]{0,60})/i)?.[0]}
export function parseRimiLeafletPage(text:string,page:number,leaflet:RimiLeaflet){const source=clean(text),offers:RawOffer[]=[],seen=new Set<string>(),anchors=[...source.matchAll(/(?:IKI\s+)?-([1-9]\d?)%/gi)],onePlus=[...source.matchAll(/\b1\s*\+\s*1\b/g)],detected=anchors.length+onePlus.filter(match=>!anchors.some(anchor=>Math.abs((anchor.index??0)-(match.index??0))<100)).length;const add=(row:RawOffer|undefined)=>{if(!row)return;const key=`${normalizeName(row.name)}|${row.salePrice??""}`;if(!seen.has(key)){seen.add(key);offers.push(row)}};
  anchors.forEach((anchor,index)=>{const start=anchor.index??0,end=start+anchor[0].length,previous=index?((anchors[index-1].index??0)+anchors[index-1][0].length):0,next=index<anchors.length-1?(anchors[index+1].index??source.length):source.length,before=source.slice(previous,start),after=source.slice(end,next),beforePair=before.match(/(\d{1,3}[,.]\d{2})\s+(\d{1,3}[,.]\d{2})\s*$/),afterPair=after.match(/^\s*(\d{1,3}[,.]\d{2})\s+(\d{1,3}[,.]\d{2})/);let name:string|undefined,salePrice:number|undefined,regularPrice:number|undefined;if(beforePair){salePrice=parsePrice(beforePair[1]);regularPrice=parsePrice(beforePair[2]);name=candidate(before.slice(0,beforePair.index),"last")}else if(afterPair){salePrice=parsePrice(afterPair[1]);regularPrice=parsePrice(afterPair[2]);const beforeName=candidate(before,"last"),afterName=candidate(after.slice((afterPair.index??0)+afterPair[0].length),"first"),beforeBelongsToPrevious=/^\s*\d{1,3}[,.]\d{2}\s+\d{1,3}[,.]\d{2}/.test(before);name=beforeName&&!beforeBelongsToPrevious?beforeName:afterName??beforeName}else name=candidate(after,"first")??candidate(before,"last");if(salePrice!=null&&regularPrice!=null&&salePrice>=regularPrice){salePrice=undefined;regularPrice=undefined}add(offer(name??"",salePrice,regularPrice,Number(anchor[1]),leaflet,page,condition(`${before} ${after}`)))});
  for(const match of source.matchAll(/-([1-9]\d?)%\s+(\d{1,3}[,.]\d{2})\s+(\d{1,3}[,.]\d{2})\s+([A-Za-zĄČĘĖĮŠŲŪŽąčęėįšųūž][\s\S]{2,190}?(?:(?:\d+(?:[,.]\d+)?\s*(?:kg|g|l|ml|vnt\.?))|(?:\(\d+\s*rūš(?:is|ys|ių)\))))/gi)){const sale=parsePrice(match[2]),regular=parsePrice(match[3]),percent=Number(match[1]);if(sale!=null&&regular!=null&&sale<regular&&!offers.some(row=>row.salePrice===sale&&row.regularPrice===regular&&row.discountPercent===percent))add(offer(match[4],sale,regular,percent,leaflet,page,condition(match[0])))}
  for(const mechanic of onePlus){if(anchors.some(anchor=>Math.abs((anchor.index??0)-(mechanic.index??0))<100))continue;const name=candidate(source.slice(Math.max(0,(mechanic.index??0)-220),mechanic.index),"last");add(offer(name??"",undefined,undefined,undefined,leaflet,page,"1+1"))}
  const parsedBlocks=Math.min(detected,offers.length);return{detected,parsedBlocks,offers,rejected:detected-parsedBlocks};
}
export function buildRimiLeafletAudit(leaflets:RimiLeaflet[],today=new Date().toISOString().slice(0,10)):RimiLeafletAudit{const active=leaflets.filter(item=>item.validFrom<=today&&item.validUntil>=today),audit:RimiLeafletAudit={activeLeaflets:active.length,pages:0,detectedBlocks:0,parsedBlocks:0,validOffers:0,rejected:0,rejections:{},offers:[]};for(const leaflet of active)leaflet.pageTexts.forEach((text,index)=>{audit.pages++;const page=parseRimiLeafletPage(text,index+1,leaflet);audit.detectedBlocks+=page.detected;audit.parsedBlocks+=page.parsedBlocks;audit.validOffers+=page.offers.length;audit.rejected+=page.rejected;audit.offers.push(...page.offers.filter(row=>retainNonPorkOffer(row,"rimi","rimi-leaflet")));if(page.rejected)audit.rejections["unsupported or non-product promotion mechanic"]=(audit.rejections["unsupported or non-product promotion mechanic"]??0)+page.rejected});return audit}
const tokens=(name:string)=>new Set(normalizeName(name).split(" ").filter(token=>token.length>2&&!/^\d/.test(token)));
function sameProduct(leaflet:RawOffer,product:RimiEshopProduct){if(leaflet.quantity!=null&&product.quantity!=null&&(leaflet.unit!==product.unit||Math.abs(leaflet.quantity-product.quantity)>.001))return false;const a=tokens(leaflet.name),b=tokens(product.name),shared=[...a].filter(token=>b.has(token)).length;return shared>=3&&shared/Math.max(a.size,b.size)>=.72}
export function collapseLeafletAlternatives(offers:RawOffer[]){const groups=new Map<string,RawOffer[]>();for(const row of offers){const key=`${row.publicationId??""}|${row.page??""}|${row.externalId??normalizeName(row.name)}`,group=groups.get(key)??[];group.push(row);groups.set(key,group)}const result:RawOffer[]=[];for(const group of groups.values()){const priced=group.filter(row=>row.salePrice!=null&&row.regularPrice!=null),selected=priced.length?priced:group,unique=new Map<string,RawOffer>();for(const row of selected){const key=`${row.salePrice??""}|${row.regularPrice??""}`,previous=unique.get(key);unique.set(key,previous?{...previous,...Object.fromEntries(Object.entries(row).filter(([,value])=>value!=null&&value!==""))}:row)}result.push(...unique.values())}return result}
export function mergeRimiSources(leafletOffers:RawOffer[],eshopOffers:RawOffer[],products:RimiEshopProduct[]){let matched=0,priceConflicts=0;const candidates=collapseLeafletAlternatives(leafletOffers),enriched=candidates.map(leaflet=>{const product=products.find(candidate=>sameProduct(leaflet,candidate));if(!product)return leaflet;matched++;if(product.currentPrice!=null&&leaflet.salePrice!=null&&Math.abs(product.currentPrice-leaflet.salePrice)>.001)priceConflicts++;return{...leaflet,name:product.name,externalId:product.externalId,brand:product.brand??leaflet.brand,quantity:product.quantity??leaflet.quantity,unit:product.unit??leaflet.unit,imageUrl:product.imageUrl??leaflet.imageUrl,leafletSourceUrl:leaflet.leafletSourceUrl??leaflet.sourceUrl,sourceUrl:product.sourceUrl,onlineAvailable:product.onlineAvailable,ecommercePrice:product.currentPrice,leafletImageUrl:leaflet.imageUrl} as RawOffer}),cleaned=collapseLeafletAlternatives(enriched),leafletKeys=new Set(cleaned.map(item=>item.externalId?`id:${item.externalId}`:`name:${normalizeName(item.name)}|${item.quantity??""}|${item.unit??""}`)),eshopOnly=eshopOffers.filter(item=>!leafletKeys.has(item.externalId?`id:${item.externalId}`:`name:${normalizeName(item.name)}|${item.quantity??""}|${item.unit??""}`)).map(item=>({...item,promotionSource:"eshop" as const,promotionActive:true,onlineAvailable:true,physicalStoreAvailability:"unknown" as const}));return{offers:[...cleaned,...eshopOnly],matched,unmatched:candidates.length-matched,eshopOnly:eshopOnly.length,priceConflicts}}
